export const GET_ALL_PREVENTIONS_REQUEST = 'GET_ALL_PREVENTIONS_REQUEST';
export const GET_ALL_PREVENTIONS_SUCCESS = 'GET_ALL_PREVENTIONS_SUCCESS';
export const GET_ALL_PREVENTIONS_FAILURE = 'GET_ALL_PREVENTIONS_FAILURE';
