spring:
  application:
    name: gateway-server


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path= /auth/** , /api/admin/users/** , /api/users/** , /users/**


            - id: CATEGORY-SERVICE
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path= /api/categories/**, api/categories/company-admin/**


            - id: FINANCING-COMPANY-SERVICE
              uri: lb://FINANCING-COMPANY-SERVICE
              predicates:
                - Path= /api/companies/**


            - id: FINANCING-OPPORTUNITY
              uri: lb://FINANCING-OPPORTUNITY
              predicates:
                - Path= /api/financing-opportunity/** , /api/opportunity/companyAdmin/**


            - id: INTERVIEW-BOOKING
              uri: lb://INTERVIEW-BOOKING
              predicates:
                - Path= /api/interview-booking/**


            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path= /api/payments/**


            - id: PREVENTION-SERVICE
              uri: lb://PREVENTION-SERVICE
              predicates:
                - Path= /api/preventions/** , /api/preventions/companyAdmin"

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
server:
  port: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    prefer-ip-address: true