spring:
  application:
    name: interview-booking
  datasource:
    url: jdbc:mysql://localhost:3306/interviewbookingdb_NN
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 5005


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    prefer-ip-address: true