export const CREATE_OPPORTUNITY_REQUEST = 'CREATE_OPPORTUNITY_REQUEST';
export const CREATE_OPPORTUNITY_SUCCESS = 'CREATE_OPPORTUNITY_SUCCESS';
export const CREATE_OPPORTUNITY_FAILURE = 'CREATE_OPPORTUNITY_FAILURE';

export const GET_COMPANY_OPPORTUNITIES_REQUEST = 'GET_COMPANY_OPPORTUNITIES_REQUEST';
export const GET_COMPANY_OPPORTUNITIES_SUCCESS = 'GET_COMPANY_OPPORTUNITIES_SUCCESS';
export const GET_COMPANY_OPPORTUNITIES_FAILURE = 'GET_COMPANY_OPPORTUNITIES_FAILURE';
